# Generated by Django 4.2.16 on 2026-08-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(max_length=64, unique=True, verbose_name='شناسه چت')),
                ('state', models.CharField(blank=True, default='', max_length=64, verbose_name='وضعیت')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='داده')),
            ],
            options={
                'verbose_name': 'گفتگوی ربات',
                'verbose_name_plural': 'گفتگوهای ربات',
            },
        ),
    ]
