# Generated by Django 4.2.16 on 2026-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bale_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaleBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='اگر خاموش باشد، polling پیام\u200cها را پردازش نمی\u200cکند', verbose_name='فعال بودن ربات')),
                ('bot_token', models.CharField(blank=True, default='', help_text='توکن دریافتی از BotFather', max_length=255, verbose_name='توکن ربات بله')),
                ('api_base', models.CharField(blank=True, default='https://tapi.bale.ai', max_length=255, verbose_name='آدرس API بله')),
            ],
            options={
                'verbose_name': 'تنظیمات ربات بله',
                'verbose_name_plural': 'تنظیمات ربات بله',
            },
        ),
    ]
