# Generated by Django 4.2.16 on 2026-01-06 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='فروشگاه', help_text='نام فروشگاه یا سایت', max_length=200, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, help_text='لوگوی سایت (JPG, PNG, SVG, WebP)', null=True, upload_to='settings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])], verbose_name='لوگو')),
                ('copyright_text', models.CharField(default='© تمامی حقوق محفوظ است', help_text='متن کپی رایت که در footer نمایش داده می\u200cشود', max_length=500, verbose_name='متن کپی رایت')),
                ('contact_phone', models.CharField(blank=True, help_text='شماره تماس فروشگاه', max_length=20, null=True, verbose_name='شماره تماس')),
                ('contact_email', models.EmailField(blank=True, help_text='ایمیل فروشگاه', max_length=254, null=True, verbose_name='ایمیل')),
                ('contact_address', models.TextField(blank=True, help_text='آدرس فروشگاه', null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, help_text='توضیحات کوتاه درباره فروشگاه', null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
