# Generated by Django 4.2.16 on 2026-08-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_catalog_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='landing_ab_enabled',
            field=models.BooleanField(default=False, help_text='اگر روشن باشد، بین تم اصلی و تم B به\u200cصورت تصادفی انتخاب می\u200cشود', verbose_name='فعال\u200cسازی A/B لندینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_ab_split',
            field=models.PositiveSmallIntegerField(default=50, help_text='درصد بازدیدکنندگانی که تم اصلی (A) را می\u200cبینند (۰ تا ۱۰۰)', verbose_name='درصد نمایش تم A'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='landing_theme_b',
            field=models.CharField(choices=[('cinema', 'سینمایی'), ('neon', 'نئون'), ('fresh', 'روشن'), ('editorial', 'تحریریه')], default='neon', help_text='تم جایگزین برای تست A/B', max_length=20, verbose_name='تم لندینگ B'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='service_enabled',
            field=models.BooleanField(default=False, help_text='اگر روشن باشد و مبلغ بیشتر از صفر باشد، برای سفارش\u200cهایی که حداقل یک محصول با تیک سرویس دارند یک\u200cبار اعمال می\u200cشود', verbose_name='فعال\u200cسازی سرویس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='service_fee',
            field=models.PositiveIntegerField(default=0, help_text='مبلغ ثابت سرویس (ریال). روی کل فاکتور فقط یک\u200cبار اضافه می\u200cشود', verbose_name='مبلغ سرویس (ریال)'),
        ),
        migrations.CreateModel(
            name='LandingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'نمایش لندینگ'), ('start', 'شروع سفارش')], max_length=20, verbose_name='نوع رویداد')),
                ('theme', models.CharField(max_length=20, verbose_name='تم')),
                ('session_key', models.CharField(blank=True, default='', max_length=64, verbose_name='کلید نشست')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'رویداد لندینگ',
                'verbose_name_plural': 'رویدادهای لندینگ',
                'indexes': [models.Index(fields=['event_type', 'theme', '-created_at'], name='core_landin_event_t_73c8fa_idx'), models.Index(fields=['theme', '-created_at'], name='core_landin_theme_b55e8b_idx')],
            },
        ),
    ]
