# Generated by Django 4.2.16 on 2026-08-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_landing_palette_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cart_layout',
            field=models.CharField(choices=[('side', 'کناری (عمودی)'), ('bottom', 'پایین صفحه (افقی)')], default='side', help_text='محل نمایش سبد روی صفحه منوی کیوسک', max_length=20, verbose_name='چیدمان سبد خرید'),
        ),
    ]
