# Generated by Django 4.2.16 on 2026-01-06 16:42

from django.db import migrations, models
import django.db.models.deletion


def populate_product_name(apps, schema_editor):
    """
    Populate product_name from product.name for existing OrderItems.
    """
    OrderItem = apps.get_model('orders', 'OrderItem')
    for order_item in OrderItem.objects.filter(product__isnull=False):
        if order_item.product:
            order_item.product_name = order_item.product.name
            order_item.save(update_fields=['product_name'])


def reverse_populate_product_name(apps, schema_editor):
    """
    Reverse migration - no action needed.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_assign_default_category_and_make_required'),
        ('orders', '0003_add_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, help_text='نام محصول در زمان ثبت سفارش (برای نمایش در صورت حذف محصول)', max_length=255, null=True, verbose_name='نام محصول (بکاپ)'),
        ),
        migrations.RunPython(
            populate_product_name,
            reverse_populate_product_name,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='در صورت حذف محصول، این فیلد null می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='محصول'),
        ),
    ]
