# Generated by Django 4.2.16 on 2026-08-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_fulfillment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(help_text='درصد (۰–۱۰۰) یا مبلغ ثابت به ریال', verbose_name='مقدار')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, help_text='فقط برای تخفیف درصدی؛ خالی = بدون سقف', null=True, verbose_name='سقف تخفیف (ریال)')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='خالی = نامحدود', null=True, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده\u200cشده')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='کد کوپن (بکاپ)'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='landing_theme',
            field=models.CharField(blank=True, default='', help_text='تم A/B که منجر به این سفارش شده', max_length=20, verbose_name='تم لندینگ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=list, help_text='لیست {id, name, group_name, price_delta}', verbose_name='آپشن\u200cهای انتخاب\u200cشده'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'payment_status'], name='orders_orde_created_f3ae18_idx'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='کوپن'),
        ),
    ]
