# Generated by Django 4.2.16 on 2026-08-08 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bale_chat_id', models.CharField(blank=True, help_text='chat_id کاربر در پیام\u200cرسان بله', max_length=64, null=True, unique=True, verbose_name='شناسه چت بله')),
                ('bale_enabled', models.BooleanField(default=False, help_text='اگر فعال باشد، کاربر می\u200cتواند با ربات بله کار کند', verbose_name='دسترسی ربات بله')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'permissions': [('view_reports', 'مشاهده گزارشات'), ('view_products', 'مشاهده محصولات'), ('add_products', 'افزودن محصول'), ('change_products', 'ویرایش محصول'), ('delete_products', 'حذف محصول'), ('change_stock', 'تغییر موجودی'), ('view_categories', 'مشاهده دسته\u200cبندی'), ('add_categories', 'افزودن دسته\u200cبندی'), ('change_categories', 'ویرایش دسته\u200cبندی'), ('delete_categories', 'حذف دسته\u200cبندی'), ('view_orders', 'مشاهده سفارشات'), ('change_orders', 'تغییر وضعیت سفارش'), ('change_settings', 'تغییر تنظیمات'), ('manage_users', 'مدیریت کاربران و گروه\u200cها')],
            },
        ),
    ]
