# Generated by Django 4.2.16 on 2026-08-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_service_fee_applicable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='نام گروه')),
                ('min_select', models.PositiveSmallIntegerField(default=0, verbose_name='حداقل انتخاب')),
                ('max_select', models.PositiveSmallIntegerField(default=1, verbose_name='حداکثر انتخاب')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گروه آپشن محصول',
                'verbose_name_plural': 'گروه\u200cهای آپشن محصول',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='نام')),
                ('price_delta', models.IntegerField(default=0, help_text='مبلغ اضافه\u200cشونده به قیمت پایه محصول', verbose_name='تغییر قیمت (ریال)')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productoptiongroup', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'آپشن محصول',
                'verbose_name_plural': 'آپشن\u200cهای محصول',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
